### ISSUE TITLE
sphinx 1.7

### ISSUE THREAD

**Issue by miki208** [delta003/RunestoneComponents#2]
Da li neko ima problem sa build-ovanjem kad se instalira najnoviji sphinx?
Video sam da imaju issue identican ovome koji ja imam, tacnije paverutils ima problem kad pozove sphinx-build preko funkcije "dry". Kad se sphinx-build pozove u terminalu, lagano prolazi. Privremeni fix je da se sphinx downgrade-uje na 1.6.3

Ukoliko se i vama javlja takav problem kada build-ujete, bilo bi dobro da se u requirements fiksira verzija 1.6.3 za sphinx.

**Comment by delta003** [comment]
U sustini sam protiv koriscenja >= u requirements.txt tako da se slazem sa fiksiranjem verzije ako to resava problem. Mergovacu PR. Hvala!
